#!/usr/bin/env python3
import json
import os
import glob

# --- CONFIG ---
home = os.path.expanduser("~")
local_state_path = os.path.join(home, ".config", "google-chrome", "Local State")
bin_dir = os.path.join(home, ".config", "i3", "chrome-sync")
SIGNATURE = "# Auto-generated by chrome-profile-sync"

if not os.path.exists(bin_dir):
    os.makedirs(bin_dir)

# 1. READ CHROME CONFIG
try:
    with open(local_state_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
except Exception as e:
    print(f"Error reading Chrome config: {e}")
    exit(1)

profiles = data.get("profile", {}).get("info_cache", {})
valid_filenames = []

# 2. CREATE/UPDATE SCRIPTS
for directory_name, info in profiles.items():
    identifier = info.get("user_name") or info.get("name")
    if not identifier:
        continue

    safe_name = identifier.lower().replace(" ", "-")
    script_name = f"chrome-{safe_name}"
    script_path = os.path.join(bin_dir, script_name)
    
    valid_filenames.append(script_name)

    directory_escaped = directory_name.replace("'", "'\\''")
    bash_content = (
        f"#!/usr/bin/env bash\n"
        f"{SIGNATURE}\n"
        f"printf '%s' '{directory_escaped}' > ~/.config/i3/.chrome-launched\n"
        f"exec google-chrome-stable --profile-directory=\"{directory_name}\" --new-window \"$@\"\n"
    )

    with open(script_path, "w") as f:
        f.write(bash_content)
    os.chmod(script_path, 0o755)

# 3. CLEANUP OLD SCRIPTS
for existing_file in glob.glob(os.path.join(bin_dir, "chrome-*")):
    filename = os.path.basename(existing_file)
    if filename not in valid_filenames and filename != "chrome-sync":
        try:
            with open(existing_file, 'r') as f:
                if SIGNATURE in f.read(100):
                    os.remove(existing_file)
        except:
            pass
